fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    inifile: git://github.com/puppetlabs/puppetlabs-inifile.git
    rbenv: git://github.com/justindowning/puppet-rbenv.git
  symlinks:
    splunk: "#{source_dir}"
